### ISSUE TITLE
Improve VPN auto connect UX

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/furyctl#163]
Needs discussion, some things to decide:
- how to handle failures
- when to connect automatically
- when to disconnect automatically
- how, what and when inform the user

**Comment by omissis** [comment]
We discussed it today, and we decided to introduce a few flags and behaviours.
In a nutshell, we will support interactive, non-interactive and auto-connect modes, both when going full-circle and during single phases.
In order to support all of that, we will be introducing two new, mutually-exclusive flags: `--vpn-skip` and `--vpn-auto-connect`.
Note that all the cases discussed in this issue are valid only for private clusters, as public ones do not need a vpn in that the api server can be reached directly from the internet.

See a few examples below:

### Example 1

Command: `furyctl create cluster furyctl.yaml`

Notes:
- the command suspend the execution at the beginning of the `kubernetes` phase, printing an example command to run for connecting to the vpn, and waits for user confirmation (a simple `Press Enter` will do)
- this behaviour allows the user to pick their preferred way to connect to the vpn server, and it shows how to do so on the command line using openvpn and the fury-generated certificate, if the vpn section is filled in in the provided furyctl.yaml

### Example 2

Command: `furyctl create cluster furyctl.yaml --vpn-skip`

Notes:
- the behaviour is almost the same same as the example 1, but furyctl does not wait for the user to press enter to continue
- this case assumes the vpn connection was already established

### Example 3

Command: `furyctl create cluster furyctl.yaml --vpn-auto-connect`

Notes:
- At the beginning of the `kubernetes` and `distribution` phases furyctl checks that there are no other openvpn processes, in order to avoid conflicts
- Once furyctl terminates, it does not disconnect from the vpn: it prints the instructions for disconnecting from it though, should the users desire to do so

### Example 4

Command: `furyctl create cluster furyctl.yaml --vpn-auto-connect --vpn-skip`

Notes: 
- This case must return an error as we do not support the two flags at the same time

**Comment by omissis** [comment]
@Al-Pragliola sLet's implement a prompt for the user to choose if exiting (CTRL-C) or continuing (ENTER) when furyctl detects and already existing openvpn connection
